from enum import Enum 


class EventType:
    TICK = 'EVENT_TICK'
    ORDER = 'EVENT_ORDER'
    ORDER_SUCCESS = 'EVENT_ORDER_SUCCESS'
    ORDER_ERROR = 'EVENT_ORDER_ERROR'
    CANCEL_SUCCESS = 'EVENT_CANCEL_SUCCESS'
    CANCEL_ERROR = 'EVENT_CANCEL_ERROR'
    TRADE = 'EVENT_TRADE'
    L2TICK = 'EVENT_L2TICK'
    L2OrdTrac = 'EVENT_L2OrdTrac'
    ...